baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Web site Oscar'
theme ="relearn"

  [[params.themeVariant]]
    auto = ['learn', 'neon']
    identifier = 'retro-auto'
    name = 'Retro Learn/Neon'

